Repository ExpTechTW/docs, pull requests merged in 2024-06, with the labels that each got.

#1 Cdps
  docs/cdps/command/index.mdx
  docs/cdps/config/index.mdx
  docs/cdps/develop/index.mdx
  docs/cdps/intro.md
  docs/cdps/more/dependencies.mdx
  docs/cdps/more/events.mdx
  docs/cdps/more/focus-load.mdx
  docs/cdps/more/index.mdx
  docs/cdps/more/inject.mdx
  docs/cdps/more/log.mdx
  docs/cdps/more/pip.mdx
  docs/cdps/more/plugin.mdx
  docs/cdps/more/pre-load.mdx
  docs/cdps/more/thread.mdx
  docs/cdps/more/tree.mdx
  docs/cdps/more/version.mdx
  docs/cdps/plugin/event.mdx
  docs/cdps/plugin/file.mdx
  docs/cdps/plugin/index.mdx
  docs/cdps/plugin/more.mdx
  docs/cdps/plugin/pack.mdx
  docs/cdps/plugin/start.mdx
  docs/cdps/plugins/index.mdx
  docs/cdps/release/index.mdx
  docs/cdps/start/index.mdx
  docs/cdps/start/install.mdx
  docusaurus.config.ts
  i18n/en/docusaurus-plugin-content-docs/current/cdps/intro.md
  i18n/en/docusaurus-theme-classic/footer.json
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/intro.md
  i18n/ja/docusaurus-theme-classic/footer.json
Labels: size/XL

#5 CDPS
  .prettierrc
  docs/cdps/command/index.mdx
  docs/cdps/config/index.mdx
  docs/cdps/develop/index.mdx
  docs/cdps/more/dependencies.mdx
  docs/cdps/more/event.mdx
  docs/cdps/more/events_list.mdx
  docs/cdps/more/focus_load.mdx
  docs/cdps/more/index.mdx
  docs/cdps/more/inject.mdx
  docs/cdps/more/log.mdx
  docs/cdps/more/pip.mdx
  docs/cdps/more/plugin.mdx
  docs/cdps/more/pre_load.mdx
  docs/cdps/more/thread.mdx
  docs/cdps/more/tree.mdx
  docs/cdps/more/version.mdx
  docs/cdps/plugin/event.mdx
  docs/cdps/plugin/file.mdx
  docs/cdps/plugin/index.mdx
  docs/cdps/plugin/more.mdx
  docs/cdps/plugin/pack.mdx
  docs/cdps/plugin/start.mdx
  docs/cdps/plugins/color_log.mdx
  docs/cdps/plugins/discordwebhook.mdx
  docs/cdps/plugins/example.mdx
  docs/cdps/plugins/index.mdx
  docs/cdps/plugins/report.mdx
  docs/cdps/plugins/websocketclient.mdx
  docs/cdps/release/index.mdx
  docs/cdps/start/index.mdx
  docs/cdps/start/install.mdx
  i18n/en/docusaurus-theme-classic/footer.json
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/develop/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/dependencies.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/events_list.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/pip.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/more.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/color_log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/websocketclient.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/release/index.mdx
  i18n/ja/docusaurus-theme-classic/footer.json
Labels: size/XL

#3 i18n: japanese
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/command/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/config/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/dependencies.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/events_list.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/focus_load.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/inject.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/pip.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/plugin.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/pre_load.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/thread.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/tree.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/more/version.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/event.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/file.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/more.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/pack.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/start.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/color_log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/discordwebhook.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/example.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/report.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/websocketclient.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/start/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/start/install.mdx
Labels: size/XL

#6 fix(cdps): new component & style fixes
  docs/cdps/develop/index.mdx
  docs/cdps/miscellaneous/dependencies.mdx
  docs/cdps/miscellaneous/event.mdx
  docs/cdps/miscellaneous/events_list.mdx
  docs/cdps/miscellaneous/focus-load.mdx
  docs/cdps/miscellaneous/index.mdx
  docs/cdps/miscellaneous/inject.mdx
  docs/cdps/miscellaneous/log.mdx
  docs/cdps/miscellaneous/pip.mdx
  docs/cdps/miscellaneous/plugin.mdx
  docs/cdps/miscellaneous/pre-load.mdx
  docs/cdps/miscellaneous/thread.mdx
  docs/cdps/miscellaneous/tree.mdx
  docs/cdps/miscellaneous/version.mdx
  docs/cdps/plugin/index.mdx
  docs/cdps/plugin/more.mdx
  docs/cdps/plugins/color_log.mdx
  docs/cdps/plugins/discordwebhook.mdx
  docs/cdps/plugins/example.mdx
  docs/cdps/plugins/index.mdx
  docs/cdps/plugins/report.mdx
  docs/cdps/plugins/websocketclient.mdx
  docs/cdps/release/index.mdx
  i18n/en/code.json
  i18n/en/docusaurus-plugin-content-docs/current.json
  i18n/en/docusaurus-theme-classic/footer.json
  i18n/ja/code.json
  i18n/ja/docusaurus-plugin-content-blog/options.json
  i18n/ja/docusaurus-plugin-content-docs/current.json
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/develop/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/dependencies.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/events-list.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/focus-load.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/inject.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/pip.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/plugin.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/pre_load.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/thread.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/tree.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/version.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/more.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/color_log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/discordwebhook.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/example.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/report.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/websocketclient.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/release/index.mdx
  i18n/ja/docusaurus-theme-classic/footer.json
  i18n/ja/docusaurus-theme-classic/navbar.json
  src/components/GithubAuthor/index.tsx
  src/components/GithubAuthor/styles.module.css
  src/components/GithubRepositoryLink/index.tsx
  src/components/GithubRepositoryLink/styles.module.css
  src/components/PluginMetaBar/index.tsx
  src/components/PluginMetaBar/styles.module.css
  static/img/github.svg
Labels: size/XL

#7 fix(cdps): bad unordered list usage
  docs/api/earthquake/index.mdx
  docs/api/weather/index.mdx
  docs/cdps/command/index.mdx
  docs/cdps/config/index.mdx
  docs/cdps/develop/index.mdx
  docs/cdps/miscellaneous/dependencies.mdx
  docs/cdps/miscellaneous/event.mdx
  docs/cdps/miscellaneous/events_list.mdx
  docs/cdps/miscellaneous/focus-load.mdx
  docs/cdps/miscellaneous/index.mdx
  docs/cdps/miscellaneous/inject.mdx
  docs/cdps/miscellaneous/log.mdx
  docs/cdps/miscellaneous/pip.mdx
  docs/cdps/miscellaneous/plugin.mdx
  docs/cdps/miscellaneous/pre-load.mdx
  docs/cdps/miscellaneous/thread.mdx
  docs/cdps/miscellaneous/version.mdx
  docs/cdps/plugin/event.mdx
  docs/cdps/plugin/file.mdx
  docs/cdps/plugin/index.mdx
  docs/cdps/plugin/pack.mdx
  docs/cdps/plugin/start.mdx
  docs/cdps/plugins/color_log.mdx
  docs/cdps/plugins/websocketclient.mdx
  docs/cdps/start/index.mdx
  docs/cdps/start/install.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/command/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/config/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/develop/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/dependencies.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/events-list.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/focus-load.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/inject.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/pip.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/plugin.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/pre_load.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/thread.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/tree.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/miscellaneous/version.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/event.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/file.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/pack.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugin/start.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/color_log.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/discordwebhook.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/report.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/plugins/websocketclient.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/release/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/start/index.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/cdps/start/install.mdx
  i18n/ja/docusaurus-plugin-content-docs/current/js/installation.mdx
Labels: size/XXL

#8 feat :Dockerfile
  .github/workflows/deploy.yml
  Dockerfile
Labels: size/M

#9 fix: deploy
  .github/workflows/deploy.yml
Labels: size/XS

#10 fix: Dockerfile & deploy
  .github/workflows/deploy.yml
  Dockerfile
Labels: size/XS

#11 fix: docusaurus.config.ts
  docusaurus.config.ts
Labels: size/XS

#12 fix: docusaurus.config.ts
  docusaurus.config.ts
Labels: size/XS

#14 Dockerfile
  .github/workflows/deploy.yml
  Dockerfile
Labels: size/M

#16 fix: deploy
  .github/workflows/deploy.yml
Labels: size/XS

#15 feat: status
  docusaurus.config.ts
  i18n/en/docusaurus-theme-classic/footer.json
  i18n/ja/docusaurus-theme-classic/footer.json
Labels: size/S

#13 fix: author
  blog/2019-05-28-first-blog-post.md
  blog/2019-05-29-long-blog-post.md
  blog/2021-08-01-mdx-blog-post.mdx
  blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  blog/2021-08-26-welcome/index.md
  blog/authors.yml
  blog/miyashooooo/2024-06-21_miyashooooo.mdx
  blog/tags.yml
  src/components/BlogMetaBar/index.tsx
  src/components/BlogMetaBar/styles.module.css
Labels: size/L
